spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console.enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher # Make Spring Boot 2.6 work with Springfox 3.0